### ISSUE TITLE
 Package missing error after install.

### ISSUE THREAD

**Issue by OGNeutron** [apollographql/federation#1065]
I've been getting this error for some reason - 

`The "@apollo/federation/dist/directives" package is missing. Please, make sure to install this library ($ npm install @apollo/federation/dist/directives) to take advantage of SchemaBuilder`

**Comment by abernix** [comment]
The file is definitely gone, so the error message is correct.  My point is that we didn't expect anyone to depend on it externally from the project, as it's not exported from the top-level of the package. 😉 

If someone is — that's okay though it'd be good to understand the use-cases, so we can discuss if we want to expose it at the top-level of the package or not!  In the meanwhile, the dependency should be updated to point to [`@apollo/subgraph`](https://npm.im/@apollo/subgraph) which is taking the place of `@apollo/federation` and will provide precisely the pieces of Federation (which includes more than just subgraphs, but also the Router/Gateway, various tooling, etc.) for Subgraph servers to allow their schema to participate in a federated architecture (rather than also including all of our composition algorithm itself, etc. – which will soon get their own dedicated packages)

That module is now available at [`@apollo/subgraph/dist/directives`](https://www.runpkg.com/?@apollo/subgraph@0.1.0/dist/directives.js) in the [published npm package](https://www.npmjs.com/package/@apollo/subgraph).

**Comment by abernix** [comment]
This is being resolved in https://github.com/nestjs/graphql/pull/1797 (and follow-ups)

**Comment by iMobs** [comment]
@abernix it's already had a breaking change to the export thanks to #1096 renaming `federationDirectives` to `directivesWithNoDefinitionNeeded`. NestJS might need a more major rewrite to not use the directives directly.

**Comment by trevor-scheer** [comment]
@iMobs happy to discuss possibly exporting these directives as part of the public API. Would you mind opening an issue (or a PR, even) which states your use case for them?

**Comment by alondon17** [comment]
@trevor-scheer type-graphql's example federation project uses this to make a schema https://github.com/MichalLytek/type-graphql/blob/master/examples/apollo-federation/helpers/buildFederatedSchema.ts
me and maybe other people copied that, and it broke when updating dependencies

**Comment by iMobs** [comment]
Looks like the owner of NestJS has done [a major refactor](https://github.com/nestjs/graphql/pull/1893) and referencing the directives is no longer an issue. AFAIK this was a fork of type-graphql and I'm not sure how much they learn from each other these days but a similar fix would probably be a good idea.
