### ISSUE TITLE
Allow `@requires` to have no fields when the entity can be resolved without needing the parent

### ISSUE THREAD

**Issue by damienpontifex** [apollographql/federation#1098]
When a subgraph that extends a type can resolve the parent type within it's own context, it should be able to result in a parallel call without waiting for the original resolver. Such a scenario is possible when the entity ID can be extracted say from a JWT auth token

An example where all subgraphs get passed the authorization token and within that token is the user id as part of the JWT.

User graph
```graphql
type User @key(fields: "id") {
    id: ID!
}

extend type Query {
    me: User!
}
```

Sub graph 2
```graphql
extend type User @key(fields: "id") {
  id: ID! @external
  otherProperty: String
}
```

Currently the federation gateway calls in sequence
1. User graph
2. Sub graph 2 only after user graph request has completed

If the `User.id` property can be resolved independently within sub graph 2, there should be a way to indicate that it doesn't require any of the fields from the originating type.

I tried defining `@requires(fields: "")` but got an error, but maybe something like this could indicate that it doesn't require fields to resolve and could hence be called without waiting for the original `User` subgraph call to resolve to the gateway first

**Comment by martijnwalraven** [comment]
To make sure I understand your use case, are you talking about a scenario where you'd execute a query like this?

```
query {
  me {
    otherProperty
  }
}
```

I don't think this really means subgraph 2 is able to resolve `User.id` independently, because there could be many other paths that require fetching user details from subgraph 2, and these do not all refer to the currently authenticated user (as extracted from a JWT auth token).

In the example below, you need to be able to fetch `otherProperty` for the authors of posts, which are unlikely to all be the currently authenticated user:

```
  query {
    topPosts {
      title
      author {
        name
        otherProperty
      }
    }
  }
```

What I think your use case is suggesting, is that there should be a way to indicate that subgraph 2 is able to independently resolve `Query.me` (by extracting a user ID from the request). This isn't currently possible, but we're working on relaxing field ownership rules in Federation to allow for different subgraphs to provide the same field, and I suspect that might offer a solution for this case as well.

**Comment by damienpontifex** [comment]
You are correct, likely the second in the broader scenario.

Our current implementation is limited to the single child under `me` and hence my limited explanation.

Are you able to link to any existing issues/PRs where this work is going on? I might be able to pull in preliminary work to trial it out if it has already begun

**Comment by pcmanus** [comment]
@damienpontifex: following up on what martijn said, the now public upcoming version of federation (federation 2.0, currently in alpha) might have a solution for this. Namely, [this test](https://github.com/apollographql/federation/blob/main/query-planner-js/src/__tests__/buildPlan.test.ts#L18-L81) demonstrate how subgraphs can declare that they can both independently resolve the `me` `User` and the query planner is able to use this.

Let us know if that would solve your issue (of course, this new version is not GA yet and shouldn't be used in production just yet, but we'd appreciate any feedback).

**Comment by damienpontifex** [comment]
Thanks @pcmanus, we'll be trialling the federation 2 pieces at work this week, so can see how it goes in fitting our need. But this definitely looks promising! Thank you

**Comment by damienpontifex** [comment]
Thanks @pcmanus this fit's our use case and gets us the performance benefit we were after. Thank you for all the great work 👍🏻
