### ISSUE TITLE
Incorrect Query Plan for Interface type queries

### ISSUE THREAD

**Issue by AneethAnand** [apollographql/federation#1375]
"@apollo/query-planner": "2.0.0-alpha.3",

### Subgraph1 Schema
```
  const subgraph1 = {
    name: 'Subgraph1',
    typeDefs: gql`
      type Query {
        node(id: ID!): Node!
      }

      interface Node {
        id: ID!
      }

      type User implements Node @key(fields: "id") {
        id: ID!
        prop1: String
      }
    `
  }
```

### Subgraph2 Schema
```
  const subgraph2 = {
    name: 'Subgraph2',
    typeDefs: gql`
      type Query {
        node(id: ID!): Node!
      }

      interface Node {
        id: ID!
      }

      type Client implements Node @key(fields: "id") {
        id: ID!
        prop2: String
      }
    `
  }
```

###GraphQL Query
```
query NodeQuery{
  node(id: "456") {
	... on User {
            prop1
        }
   }
}
```

### Actual Query plan
```
  Fetch(service: "Subgraph2") {
    {
      node(id: 456) {
        __typename
      }
    }
  },
}
```

## Expected Behavior 
1) the query plan should be formulated for "Subgraph1" where User type has been defined.

## Bug Identification
```
`${selection.selectionSet}`
'{ ... on User { prop1 } }'
`${this.stack}`
'... on User { prop1 },Query(Subgraph1) --[node]--> Node(Subgraph1) (types: [User]),Query(Subgraph2) --[node]--> Node(Subgraph2) (types: [Client])'
`${selection}`
'... on User { prop1 }'
`${options}`
'Query(Subgraph1) --[node]--> Node(Subgraph1) (types: [User]),Query(Subgraph2) --[node]--> Node(Subgraph2) (types: [Client])'

```

Per the code we consider 2 options for selection `{ ... on User { prop1 } }`
But then one of the option fails as Subgraph2 does not define the type "User"

```
`${allOptions}`
'Query(Subgraph1) --[node]--> Node(Subgraph1) --[... on User]--> User(Subgraph1) (types: [User])'
`${option}`
'Query(Subgraph1) --[node]--> Node(Subgraph1) (types: [User])'
`${option}`
'Query(Subgraph2) --[node]--> Node(Subgraph2) (types: [Client])'
`${advanceOptionsToString(options)}`
'<unsatisfiable branch>'
```

But since the "followupForOption" Subgraph2 is not possible the code returns immediately without considering the option that has been identified for Subgraph1

```
      if (followupForOption.length === 0) {

        if (operation.kind === 'FragmentElement') {
          this.closedBranches.push([option.paths.map(p => terminateWithNonRequestedTypenameField(p))]);
        }
        return;
      }
```

I think it should have been
```
        if (newOptions.length == 0 && i == options.length && operation.kind === 'FragmentElement') {
          this.closedBranches.push([option.paths.map(p => terminateWithNonRequestedTypenameField(p))]);
          return;
        }
```

If we have worked on all options and it is the last option and no other options before resulted in a solution, then terminate and return.

**Comment by pcmanus** [comment]
There is something subtle going on here, and while the current behavior is incorrect and needs fixing, I don't think it can work as you intend in that example (tldr; I think this example should not compose).

I suspect the misunderstanding here is on what it means for 2 subgraphs to resolve the same field (`node` here; it's a top-level query here, but you could make an equivalent example with it being some entity field).

The way it works in federation is that if a field can be resolved from multiple subgraphs, then it should resolve the "same way" from all subgraphs. Meaning that it should resolve to the same fundamental entity/value regarless of which subgraph resolve it (to clarify, not all the subgraphs have to resolve the same set of sub-fields on the returned entity/value but it has to be the same entity/value).

To illustrate, if 2 subgraphs A and B can resolve the author of a book, then any particular given book `b`, both A and B should resolve the same author. Note that federation cannot really force you to do so (because we don't control resolvers), but it is still very much expected. I'll note that this is what the sentence in bold toward the end of  https://www.apollographql.com/docs/federation/entities/#resolving-another-subgraphs-field-advanced essentially points to (noting that in federation 0.x, `@provides` is the only way to have a field resolvable from 2 subgraphs).

Again, if A resolves the author of book "Foo" as "Joe", then B must resolve the author of book "Foo" as "Joe" and nothing else. It cannot return `null`, or not handle it at all somehow.

What it means in the example above is that if you expose the same operation `node` from both subgraphs, both subgraphs should *always* resolve `node` to the same entity (for a fixed input, but this for all possible inputs). Which hopefully highlights that something cannot work in that example: there is no way both subgraphs can return the same entity for `node(x)`, since one subgraph only ever return "users" while the other only ever return "clients".

This is kind of the logic behind the current query planner behavior: it notices that that the query can never return a result if `Subgraph2` is queried for `node`, and since querying `Subgraph1` should behave the same way for thing to be correct, it infers the query simply don't return anything. Again, this isn't to say that the current behavior is correct, since the generated query is in fact invalid. But the correct behavior, following the rule of federation, is most likely to not accept those schema in the first place.

I do get that on that specific query, it sound strange to not infer that only `Subgraph1` has `User` and only query `Subgraph1`. But my point is that this isn't a behavior that could be generalized properly. That is, the query planner cannot assume that when there is a choice of subgraphs, then there is always a way to infer which is correct and which is incorrect. 

Consider the following query for instance:
```graphql
{
  node(id: "456") {
    __typename
  }
}
```
How should federation/query-planning handle this? There is no way to know in advance which actual entity id "456" correspond to. Should it query both subgraphs? But even then (and ignoring the performance implications), how does `Subgraph2` even answers the query if "456" is a `User` and not a `Client`? It can't  return `null` in the example since `node` result is non-nullable. But even if it was nullable, what then if both subgraph return a response (which would have to be inconsistent)?

Lastly, I'll remark that this example might be hinting to the idea of "distributing" the implementatons of an interface accross subgraphs. And to be clear, federation simply does not support a way to do this currently. I'd agree that it would worth looking at how we could introduce ways to do something along those lines as it probably enable interesting use cases. But I think it's something that is not trivial and require a bit of reflexion.

**Comment by AneethAnand** [comment]
@pcmanus  Thanks for the very quick response. Yes I definitely agree on the part where we must try to throw Schema composition errors rather then the query plan finding it during runtime.

And for the thought on "distributing the implementations of an interface" How about if we can resolve the typename for the id in the gateway and then formulate the query plan.
