### ISSUE TITLE
Gateway 0.x/2.x Open Telemetry traces missing with otel collector 0.43.0+

### ISSUE THREAD

**Issue by prasek** [apollographql/federation#1500]
## Problem

[otel/opentelemetry-collector v0.43.0](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.43.0) removed deprecated legacy path ("v1/trace") support for otlp http receiver
- https://github.com/open-telemetry/opentelemetry-collector/pull/4720
- https://github.com/open-telemetry/opentelemetry-collector/issues/1968

[supergraph-demo with otel/opentelemetry-collector 0.43.0](https://github.com/apollographql/supergraph-demo/blob/main/docker-compose.otel-collector.yml#L37) shows error samples in zpages:
- http://localhost:55679/debug/tracez shows errors `http.status_code=404, http.target=/v1/trace`

<details><summary>Error Trace Spans</summary>

```
3 Requests

When                       Elapsed (sec)
----------------------------------------
2022/02/10-02:39:24.916957      .    77 trace_id: a8f6732587ff36e0e1b45c5c6e335322 span_id: 6aa3347a98d8cbbc
                                        Status{Code=Error, description=""}
                                        Attributes:{http.flavor=1.1, http.host=collector:55681, http.method=POST, http.request_content_length=5047, http.scheme=http, http.status_code=404, http.target=/v1/trace, http.wrote_bytes=19, net.host.name=collector, net.host.port=55681, net.peer.ip=172.22.0.2, net.peer.port=41562, net.transport=ip_tcp}
2022/02/10-02:39:32.619622      .    35 trace_id: 944f49a15fd55768af3df35c7f965a3f span_id: 67bb4fd243bc30ef
                                        Status{Code=Error, description=""}
                                        Attributes:{http.flavor=1.1, http.host=collector:55681, http.method=POST, http.request_content_length=30437, http.scheme=http, http.status_code=404, http.target=/v1/trace, http.wrote_bytes=19, net.host.name=collector, net.host.port=55681, net.peer.ip=172.22.0.6, net.peer.port=59220, net.transport=ip_tcp}
2022/02/10-02:39:35.647788      .    41 trace_id: 9e672ce2916c5e67929e3254dc8c3b08 span_id: c00e14f481d47c0d
                                        Status{Code=Error, description=""}
                                        Attributes:{http.flavor=1.1, http.host=collector:55681, http.method=POST, http.request_content_length=29390, http.scheme=http, http.status_code=404, http.target=/v1/trace, http.wrote_bytes=19, net.host.name=collector, net.host.port=55681, net.peer.ip=172.22.0.6, net.peer.port=59220, net.transport=ip_tcp}

TraceId means sampled request. TraceId means not sampled request.
```

</details>

## Workaround

otel/opentelemetry-collector 0.42.0 is the last release that supports `/v1/trace`
- https://github.com/apollographql/supergraph-demo/pull/396
- https://github.com/apollographql/supergraph-demo-fed2/pull/44

## Gateway 0.x Repro
- `git clone git@github.com:apollographql/supergraph-demo.git`
- bump [otel/opentelemetry-collector to 0.43.0 or 0.44.0](https://github.com/apollographql/supergraph-demo/blob/main/docker-compose.otel-collector.yml#L37)
- `make docker-up-otel-collector`
- `make smoke`
- open http://localhost:55679/debug/tracez
- see error traces with `http.status_code=404, http.target=/v1/trace`

## Gateway 2.x Repro
- `git clone git@github.com:apollographql/supergraph-demo-fed2.git`
- bump [otel/opentelemetry-collector to 0.43.0 or 0.44.0](https://github.com/apollographql/supergraph-demo-fed2/blob/main/docker-compose.otel-collector.yml#L37)
- `make docker-up-otel-collector`
- `make smoke`
- open http://localhost:55679/debug/tracez
- see error traces with `http.status_code=404, http.target=/v1/trace`

## Subgraphs
- subgraphs are also not reporting traces with otel/opentelemetry-collector 0.43+
- currently referenced https://www.npmjs.com/package/@opentelemetry/node lib is deprecated
- [Federation Docs](https://www.apollographql.com/docs/federation/opentelemetry/) should reference current otel libs

**Comment by abernix** [comment]
My understanding would be that the **collector** would (now) be accepting on only the newer `/v1/traces` end-point (instead of the deprecated `trace`), but it's the **exporter** that would _also_ have a definition of that (now, incorrect) `/v1/trace` **or** (correct) `/v1/traces`.

Could this be due to a dependency on the [deprecated `@opentelemetry/exporter-collector` npm package](https://www.npmjs.com/package/@opentelemetry/exporter-collector) which is a dependency of the [`supergraph-demo-opentelemetry`](https://www.npmjs.com/package/supergraph-demo-opentelemetry) package that you've published and that `supergraph-demo` uses [here](https://github.com/prasek/supergraph-demo-opentelemetry/blob/72b42544c562a6f71e627d076928c30bc56f5c59/src/index.ts#L3)?  It appears that package says that the default URL is `v1/trace` (which makes sense, since that used to be correct!).  It's worth noting that it still does allow setting the `url` property on the `collectorOptions` that are passed to `CollectorTraceExporter`.

It appears that the current/maintained [`@opentelemetry/exporter-trace-otlp-http`](https://www.npmjs.com/package/@opentelemetry/exporter-trace-otlp-http) both allows specifying the endpoint URL **and** defaults to the `/v1/traces` endpoint.

Thoughts?

**Comment by abernix** [comment]
Separately, it is indeed true that some of the packages listed in the documentation are deprecated — like `@opentelemetry/tracing`.
