### ISSUE TITLE
make-fetch-happen default maxSockets of 15 connections per target likely not optimal for most gateway customers

### ISSUE THREAD

**Issue by theJC** [apollographql/federation#1647]
With the change in gateway from node-fetch to make-fetch-happen as the default used in RemoteGraphQLDataSource, it is important to make sure that the out of box configuration is appropriate for the majority of Apollo Gateway customers and uses a version of the library that is up to be kept up to date with any performance/security/bug fixes.

# Problem statements:

1. make-fetch-happen uses connection pooling (why gateway was changed over to use it), but it has a default of a maximum of 15 open sockets per target service/origin.  Note that make-fetch-happen is only using http1.1, and so no multiplexing occurs over these 15 connections
3. I suspect many customers of Apollo's gateway have service mesh in place, where quite often all of their subgraphs will all be called out to via the same identical host/port combo (ie 127.0.0.1:8099) -- thus the same origin.  In a real production environment, this will most likely result in many requests having unexpected delays and latency as these requests will be queued up until one of the 15 connections free up.
4. I believe some potentially leftover (is it still needed anymore since this is now in definitelyTyped thanks to @abernix ?) workaround typescript definitions for make-fetch-happen still exists in the gateway codebase that does not expose the maxSockets option, further obscuring this from customers as being available.
5. The version of make-fetch-happen being used by gateway is two major versions behind, and will not have all available bug/performance and node version support changes.

## Short term Recommendations:

- If possible remove the typescript definitions for make-fetch-happen from the gateway code and use them from definitely typed.
- Do some tuning experimentation exercises similar to what you have done in your gateway and router benchmarking tests to come up and update to a better out of the box Apollo scenario data backed default value to use
- Document this/make this as obvious as possible for customers

## Medium term recommendation:

- Upgrade version of make-fetch-happen used by RemoteGraphQLDataSource, gateway is on a 8.x version which is two major versions behind
- The use of make-fetch-happen in the gateway used by the supergraph manager is using a now removed feature of being able to provide a cacheManager, so perhaps a transition path could be to isolated/separate out from the make-fetch-happens that is being used by RemoteGraphQLDataSource versus the supergraph manager.

## Longer term recommendation:
- Add support for an http2 based client so we can "make-multiplexing-happen" 😄 

References:
- https://github.com/npm/make-fetch-happen#opts-max-sockets
- https://nodejs.org/dist/latest-v16.x/docs/api/http.html#agentmaxsockets
- https://github.com/nodejs/node/blob/094b2ae9ba2db28254bb09207a58bd9730ff097d/lib/_http_agent.js#L300-L312
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50339
- https://github.com/apollographql/federation/blob/main/gateway-js/src/make-fetch-happen.d.ts
- https://github.com/npm/make-fetch-happen/blob/main/docs/changelog-pre-10.0.0.md

**Comment by saravind-hotstar** [comment]
@theJC Any clues how you figured out 15 was too less, we are tuning our G/W for high traffic, we would like to see if the 15 is actually less or not via metric. Is this possible

**Comment by chrskrchr** [comment]
We experienced a minor outage in our federated gateway today because of this issue.  We saw that requests were being throttled in the gateway despite the subgraph services handling the requests in a reasonable amount of time, and we ultimately traced it back to this cap on the number of sockets.  We're working around this by setting `maxSockets: Infinity` (the [Node.js default](https://nodejs.org/dist/latest-v16.x/docs/api/http.html#agentmaxsockets)) in our datasource:

```
import MakeFetchHappen from 'make-fetch-happen';
...

export class ... extends RemoteGraphQLDataSource<...> {
  constructor(...) {
    super(...);

    // https://github.com/apollographql/federation/issues/1647
    this.fetcher = MakeFetchHappen.defaults({
      maxSockets: Infinity,
    } as any);
  }
```

Although, we'd love to remove the `any` cast and use a newer version of `make-fetch-happen` per the recommendations that @theJC made in his post.

**Comment by abernix** [comment]
Thanks for the thoughtful issue interactions.  I just wanted to note that this is on our radar and we'll try to get some consideration into what it asks for prioritized soon.

I certainly think we can address the TypeScript things to make setting the value a bit less forced, but some of the questions about sane defaults are interesting lines of thought.

> * come up and update to a better out of the box Apollo scenario data backed default value to use

Connections certainly have a cost to them, so a suggesting a tuned value here might make a lot of sense.  That said, I'm not sure if there is a one-size fits all default that would actually work well and I'm on the fence if a low number is a sane default or `Infinity` is a sane default or if there is any number in between that fits the bill.  `Infinity` might saturate both the Gateway and the subgraphs (in a way that the previous behavior did not), whereas you're running into the opposite, where your (own) subgraphs handle it well.  That may not be the case for everyone.

You're right that some experimentation can help but in our experience, each graph and the complexity and number of fetches for each query can uniquely presents their own settings.  (Fwiw, we'll be much better at reacting to such things in our new [Rust-based Router runtime](https://www.apollographql.com/docs/router/) where we'll have more ability to react to pressure (memory or otherwise) than we do today in Node.js.)

**Comment by chrskrchr** [comment]
> I'm on the fence if a low number is a sane default or `Infinity` is a sane default or if there is any number in between that fits the bill.

FWIW - we convinced ourselves that `Infinity` was a sane value because:

* `Infinity` is the OOTB default that Node uses for HTTP agents:
    * https://nodejs.org/dist/latest-v16.x/docs/api/http.html#agentmaxsockets
* Today, we don't have the metrics on our end that we'd need to inform a value other than `Infinity`.  We'd considered some "nice" sounding numbers like `128`, `256`, etc..., but those were completely arbitrary values (I say "arbitrary" due to our lack of data), so `Infinity` was as good a number as any to remove this gateway bottleneck per the next bullet point.
* If we're at the point of saturating outbound sockets in the gateway b/c the pool is uncapped, it's likely that we're also in bad shape in terms of _inbound_ sockets and in-flight requests and the process is on its way to an OOM regardless.  It's on us (the app owners) to prevent this situation via horizontal scaling, admission control, etc..., not the Apollo gateway and its cap on the # of outbound sockets

**Comment by chrskrchr** [comment]
BTW - I saw @glasser and @trevor-scheer's PR below that addresses some of the typing and other issues mentioned in this thread:

https://github.com/apollographql/federation/pull/1805

Is the goal to arrive at a consensus on this `maxSockets` default prior to shipping that PR?  For us, the best outcome would be to remove our custom fetcher (with its `maxSockets` override) the next type we upgrade our `@apollo/gateway` package. 🤞

**Comment by glasser** [comment]
We (@trevor-scheer and myself pairing right now) find @chrskrchr 's arguments compelling. Also notable that there was no bound (or reuse) in the older node-fetch version. To be clear, this is only a bound on the number of *active* connections per host — there's still a limit on the number of idle connection (256, not configurable with `make-fetch-happen`).

The work in #1805 makes it easier to select your own fetcher by taking a more conservative approach to the API which more implementations support (notably, not letting you pass `Request`/`Headers` objects which might confuse a different implementation if they try to detect them with `instanceof` — this was a real issue preventing `make-fetch-happen` v9+ from working with Gateway's current code which created `node-fetch` Headers objects).  We're also upgrading `make-fetch-happen` while we're at it.  We think that since the 15 socket max was essentially a surprise regression in 0.13.2 that it would be OK for us to make this change to `maxSockets: Infinity` by default now, especially if the CHANGELOG calls this out and shows how to change back to the 15 socket behavior if you really wanted it.

I think that would involve us telling people to write in their buildService:

```
import fetcher from 'make-fetch-happen';

new RemoteGraphQLService({
  // ...
  fetcher: fetcher.defaults({maxSockets: 15}),
})
```

So we'll probably merge #1805 without this change but then get the maxSockets change in before the next alpha?

**Comment by theJC** [comment]
Sorry, was out of town and I get back and all sorts of activity!

I'll just say we had done the same exact thing as @chrskrchr and switched this to Infinity since that was effective previous setup we had before upgrading to make-node-fetch (we had previously customized our http agent being used to enable keep-alives, and didn't override the default of Infinite)

A big thanks to @chrskrchr for providing the arguments, those would have been exactly the same thrusts we would have made.

Thanks @trevor-scheer & @glasser, looks like you guys really went through with a fine-toothed comb and modernized and found some interesting bugs -- looking forward to applying the upgrade!

**Comment by theJC** [comment]
The only thing I would recommend updating in mentions in the release notes and the docs regarding  "sockets per subgraph"

I'm pretty sure maxSockets doesn't end up being per subgraph for those who are using mesh's like envoy.... it will end up being for all subgraphs.

**Comment by glasser** [comment]
"per subgraph" seemed like a reasonable shorthand here — are you running many subgraphs on the same domain, under different paths I suppose?

**Comment by theJC** [comment]
all the subgraphs are accessed via our envoy service mesh, and all share the same host/port combo, something like:

- http://127.0.0.1:4444/serviceA/graphql
- http://127.0.0.1:4444/serviceB/graphql
- http://127.0.0.1:4444/serviceC/graphql
- http://127.0.0.1:4444/serviceD/graphql
- http://127.0.0.1:4444/serviceE/graphql

@chrskrchr -- Is there any context that you can share on if y'all have something anything close to being similar for the address to your subgraphs from your gateway?

**Comment by glasser** [comment]
@theJC I tweaked the changelog a bit: https://github.com/apollographql/federation/commit/87ecbb62ffd48784a183eba1f6f42c7138a18b24

**Comment by theJC** [comment]
Thank you sir, hopefully that will help others understand the implications a little better, depending on their environment.

**Comment by chrskrchr** [comment]
> @chrskrchr -- Is there any context that you can share on if y'all have something anything close to being similar for having a common host/port for addresses to your subgraphs from your gateway?

Our internal services all have unique hostnames, so for us the "per subgraph" verbiage was already synonymous with "per host/port pair".
