### ISSUE TITLE
refactor functions used in apollo-server and the router-bridge into apollo-utils

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/federation#1841]
During [our recent work on the router-bridge]() we copy/pasted [bits of code from apollo-server](https://github.com/apollographql/federation-rs/blob/572120fdbf957a0640cb946958b9fe52207584ac/federation-2/router-bridge/js-src/plan.ts#L141) and refactored a bit as well.

It would be great if we could refactor this and use the same methods into apollo-utils

**Comment by trevor-scheer** [comment]
@glasser maybe a good argument for making this a separate package, though exported by `@apollo/server` is effectively the same.

@o0Ignition0o can this not be imported as is right now? (I haven't dug to look more closely yet)

**Comment by benweatherman** [comment]
Doing some spot-checking, it seems like a lot of the copypasta is exported already (e.g. https://github.com/apollographql/apollo-server/blob/d75c6cf3360a46ebcd944b2113438be8f549ae6f/packages/apollo-server-core/src/plugin/usageReporting/operationDerivedDataCache.ts#L5-L8)

I'm wondering if this question came about because the rooter depending on `apollo-server-core` isn't a great option? I think currently it's just depending on the query-planner, so bringing in server might be a tougher sell.

**Comment by trevor-scheer** [comment]
Just spoke with @glasser about this and we actually already have a precedent for this. We recently moved a very similar signature function (operation registry) to its own package in (`@apollo/utils.<xyz>`)[https://github.com/apollographql/apollo-utils/tree/main/packages/operationRegistrySignature], doing the same for this function and having it live as a single package makes a lot of sense.

**Comment by glasser** [comment]
yeah i believe the task is roughly:
- do a quick three-way diff between each of the component functions in router, AS, and utils to make sure they're ~identical
- add remove aliases and the top level usage reporting signature function to utils
- update AS and router to use the new package rather than their own copies
- consider whether this is a reasonable time to put https://github.com/apollographql/apollo-server/pull/6001 into play.  i think it might be — instead of it being a sorta backwards incompatible thing for two project it'll only be for one

**Comment by trevor-scheer** [comment]
Closing as complete via:
https://github.com/apollographql/apollo-utils/pull/92
https://github.com/apollographql/federation-rs/pull/120
https://github.com/apollographql/apollo-server/pull/6449
https://github.com/apollographql/apollo-server/pull/6450
