### ISSUE TITLE
Subgraph bug

### ISSUE THREAD

**Issue by NeutronScott12** [apollographql/federation#1895]
I found a rather obscure bug in the 0.4.2 @apollo/subgraph, it doesn't call resolveReference, 0.4.0 still works, but bumping up to 0.4.2 does not.

```
@ResolveField('application_owner', (of) => UserModel)
    public getApplicationOwner(@Parent() application: ApplicationModel) {
        console.log('APPLICATION_OWNER', application.application_owner_id)
        return { __typename: 'UserModel', id: application.application_owner_id }
    }

    @ResolveReference()
    async resolveReference(reference: {
        __typename: string
        id: number
    }): Promise<Application> {
        console.log('APPLICATION_RESOLVER_REFERENCE', reference.id)
        return this.applicationService.findOneById({
            where: { id: String(reference.id) },
        })
    }
```

**Comment by pcmanus** [comment]
I suspect this is due to the changes to https://github.com/apollographql/federation/pull/1747 (which somehow don't seem to have made it to the changelog). This has probably impacted some of the tools you are using (which provides `@ResolveReference()` typically, which afaict does not come from `@apollo/subgraph`) which may need update.

But pinging @trevor-scheer for more detail/followup as I wasn't followed this issue very closely.

**Comment by trevor-scheer** [comment]
Hey @NeutronScott12. It looks like you're using NestJS, I went ahead and opened an issue against their repo - please follow along over there.

https://github.com/nestjs/graphql/issues/2228
