### ISSUE TITLE
Unable to start gateway when schema uses fragment in @provides

### ISSUE THREAD

**Issue by MollardMichael** [apollographql/federation#1935]
Hello i'm trying to upgrade our federation from v1 to v2 and started by upgrading our federation (as mentioned in the documentation).

After an upgrade to
"@apollo/gateway": "2.0.5"
"apollo-server": "3.9.0"
"graphql": "16.5.0"

I tried to start the federation using the following schema

```graphql
schema
  @core(feature: "https://specs.apollo.dev/core/v0.2")
  @core(feature: "https://specs.apollo.dev/join/v0.1", for: EXECUTION) {
  query: Query
  mutation: Mutation
}

directive @core(as: String, feature: String!, for: core__Purpose) repeatable on SCHEMA

directive @join__field(
  graph: join__Graph
  provides: join__FieldSet
  requires: join__FieldSet
) on FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__owner(graph: join__Graph!) on INTERFACE | OBJECT

directive @join__type(graph: join__Graph!, key: join__FieldSet) repeatable on INTERFACE | OBJECT

enum core__Purpose {
  EXECUTION
  SECURITY
}

input InitiateCreditTransfersInput {
  accountId: ID
}

type Payload {
  payment: Payment!
    @join__field(
      graph: PAYMENT
      provides: "statusInfo{status ... on PaymentConsentPending {consent}}"
    )
}

type Mutation {
  mutation(input: InitiateCreditTransfersInput!): Payload! @join__field(graph: PAYMENT)
}

type Query {
  noop: Boolean
}

type Payment
  @join__owner(graph: ACCOUNT_STATEMENT)
  @join__type(graph: ACCOUNT_STATEMENT, key: "id")
  @join__type(graph: PAYMENT, key: "id") {
  id: ID! @join__field(graph: ACCOUNT_STATEMENT)
  statusInfo: PaymentStatusInfo! @join__field(graph: ACCOUNT_STATEMENT)
}

interface PaymentStatusInfo {
  status: String!
}

type PaymentConsentPending implements PaymentStatusInfo {
  consent: String!
  status: String!
}

type PaymentInitiated implements PaymentStatusInfo {
  status: String!
}

scalar join__FieldSet

enum join__Graph {
  ACCOUNT_STATEMENT
    @join__graph(name: "account-statement", url: "http://account-statement-live:8080/graphql")
  PAYMENT
    @join__graph(
      name: "payment"
      url: "http://payment-api-live.payment-master.svc.cluster.local:8080/graphql"
    )
}
```

## Expected behaviour

I expected the federation to start 

## Real behaviour

I have this error during federation startup
`Error: Shouldn't have ... on PaymentConsentPending { consent } with no corresponding edge on PaymentStatusInfo(payment)`

## Context

Like you can see from the schema, ACCOUNT-STATEMENT is the owner of the entity Payment but I want to provide all the info in the response on the PAYMENT graph.

I also tried to use only "statusInfo" in the field set but it's failling because it's not a LEAF type (which was working with federation v1)

I would welcome a work around if there are any.

Thank you for your time looking into this issue

**Comment by benweatherman** [comment]
To expand a bit on what's happening: the code adds edges for the query planner in `addProvidesEdge` to add all the fields from the `@provides` directive. When it sees a normal `Field` (e.g. `status` in the above example) and the query planner doesn't yet know how to get to that field+subgraph combo, it'll add an edge https://github.com/apollographql/federation/blob/733b7a90426bbc7cc0507b48a8ca29e32f73cdc6/query-graphs-js/src/querygraph.ts#L736-L749

However, when it sees a `FragmentElement` (e.g. `... on PaymentConsentPending` in the above example), it asserts that there's _already a path_ to the `PAYMENT` subgraph https://github.com/apollographql/federation/blob/733b7a90426bbc7cc0507b48a8ca29e32f73cdc6/query-graphs-js/src/querygraph.ts#L755-L758

Unfortunately, I don't understand enough of how the query planner works to know why that should be an assertion, instead of adding the new edge like in the `Field` case. Since `@provides` is saying what a subgraph can provide, it seems like we'd want to add an edge for the for the subselection for `... on PaymentConsentPending`. In the attached PR, I've made a few attempts at adding an edge, but I'm a bit in the dark on how to proceed.

Our query planning guru is on holiday at the moment, but I'm adding this info in case it sparks any ideas. At the least, once they're back, we should be able to make some progress on this issue in relatively short time.

**Comment by pcmanus** [comment]
Sorry for the delay on this. The issue was due to the fact that the type used within the `@provides` condition was not "reachable" in the subgraph except through external fields (it wasn't the type of any non-external field). This meant the process building the underlying "query graph" was (mistakenly) not adding that type (nor any related subtypes) leading to the assertion pointed above that expected things to exist that wasn't there.

Pushed #2083 to fix this. It mostly simply ensures that even types that are only pointed by external fields are added to the underlying "query graph", ensuring it's always there when we deal with `@provides`.

> I don't understand enough of how the query planner works to know why that should be an assertion, instead of adding the new edge like in the `Field` case

The fact that this assertion is triggered essentially means we don't know of a type mentioned in the `@provides`. So yes, we kind of could have fixed this by removing the assertion and instead creating the type at this point on the assumption that the reason the type is not found is that it's only reachable through that provides, but doing so would be quite a bit more involved that just adding an edge in this case: we'd have to reach back into the original subgraph source and essentially add the full type and its dependencies. So logically it's an option, but code-wise it would be a bit messy. It's cleaner to ensure we just don't miss types when we build from that source subgraph schema in the first place, which is what the proposed patch does.
