### ISSUE TITLE
Including operation name in the query execution

### ISSUE THREAD

**Issue by Glen-Moonpig** [apollographql/federation#195]
We are using the operationName field in our client->gateway requests, [as encouraged by the GraphQL spec](https://graphql.org/learn/queries/#operation-name). When Apollo Gateway builds and executes a query plan it does not include the operation name in generated queries for federated services. This makes sense because the queries that make up the execution plan are not necessarily the operation, but a smaller part of the operation for resolving certain types/fields.
**But**, we would like the federated services to know the name of the overall operation that it is receiving requests for, to facilitate logging and monitoring purposes.

I have tried modifying my RemoteGraphQLDataSource to set the operationName field in the request, but because the query in the request does not have a matching operation name, a GraphQL error is returned:

```json
{
  "errors": [
    {
      "message": "400: Bad Request",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "response": {
          "url": "https://api.something.com/",
          "status": 400,
          "statusText": "Bad Request",
          "body": {
            "errors": [
              {
                "message": "Unknown operation named \"TestOp\".",
                "extensions": {
                  "code": "INTERNAL_SERVER_ERROR",
                  "exception": {
                    "stacktrace": [
                      "GraphQLError: Unknown operation named \"TestOp\".",
                      "    at buildExecutionContext (/var/task/bundle.js:7959:15)",
                      "    at executeImpl (/var/task/bundle.js:7875:20)",
                      "    at Module.execute (/var/task/bundle.js:7850:35)",
                      "    at /var/task/bundle.js:50331:48",
                      "    at Generator.next (<anonymous>)",
                      "    at /var/task/bundle.js:50090:71",
                      "    at new Promise (<anonymous>)",
                      "    at __awaiter (/var/task/bundle.js:50086:12)",
                      "    at execute (/var/task/bundle.js:50310:20)",
                      "    at Object.<anonymous> (/var/task/bundle.js:50258:42)"
                    ]
                  }
                }
              }
            ]
          }
        },
        "exception": {
          "stacktrace": [
            "Error: 400: Bad Request",
            "    at ...
(/var/task/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:58:26)",
            "    at async sendOperation (/var/task/node_modules/@apollo/gateway/dist/executeQueryPlan.js:159:26)",
            "    at async executeFetch (/var/task/node_modules/@apollo/gateway/dist/executeQueryPlan.js:111:41)",
            "    at async executeNode (/var/task/node_modules/@apollo/gateway/dist/executeQueryPlan.js:82:17)",
            "    at async Object.executeQueryPlan (/var/task/node_modules/@apollo/gateway/dist/executeQueryPlan.js:22:27)",
            "    at async Object.ApolloGateway.executor (/var/task/node_modules/@apollo/gateway/dist/index.js:102:30)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

Would there be any interest in making the operation name available to the federated service? Either the query plan uses the operation name in the queries that it produces, or it is made available via some extension data in the request?

**Comment by johannessteu** [comment]
We'd also use this feature https://www.apollographql.com/docs/apollo-server/api/plugin/usage-reporting/#includerequest 
But right now we have all of our traces double in apollo studio. ApolloGateway will send them with the operation name and the microservice will send another query
<img width="380" alt="Bildschirmfoto 2020-10-06 um 16 48 35" src="https://user-images.githubusercontent.com/769789/95217713-ccd6ab00-07f3-11eb-99f7-33085bbf5ed0.png">

**Comment by Glen-Moonpig** [comment]
As Apollo does not currently have a solution for this we have added functionality to send the operation name in a header and read from the header in the federated service. It would be better to have it included in the request data.

**Comment by johannessteu** [comment]
We'd probably disable reporting in the microservice and only report in the gateway for now. 
But i'm not sure how the wanted behaviour is at all. Will apollo always report twice by default?

**Comment by Glen-Moonpig** [comment]
We are not using Apollo reporting at all. But will likely get that set up in future. We are running Apollo on lambda and the reporting is not really an option as it is. We will need to build something that writes the metrics to the logs and pushes them to the Apollo API out of process.

**Comment by abernix** [comment]
> We'd also use this feature [apollographql.com/docs/apollo-server/api/plugin/usage-reporting/#includerequest](https://www.apollographql.com/docs/apollo-server/api/plugin/usage-reporting/#includerequest)
> But right now we have all of our traces double in apollo studio. ApolloGateway will send them with the operation name and the microservice will send another query
> <img alt="Bildschirmfoto 2020-10-06 um 16 48 35" width="380" src="https://user-images.githubusercontent.com/769789/95217713-ccd6ab00-07f3-11eb-99f7-33085bbf5ed0.png">

Since the Gateway request traces from the implementing services that it queries, the recommendation is to not have the implementing services setup to _also_ send traces.  We used to actually have a warning message in place when this configuration had been enabled inadvertently (which, because of the fact that we activate tracing automatically when the `APOLLO_KEY` or `ENGINE_API_KEY` is set in the environment, wasn't all that hard to do.  The suggestion in this case has been to not set the key in the implementing service, but that _may_ have changed to a degree which I don't immediately recall with https://github.com/apollographql/apollo-server/pull/4453/).

While I see how it's a use case that might work for you, it seems unnatural for me for the operation name to be threaded along to the downstream service.  This is for a few reasons:

* The operation that the downstream service is merely a derivitive

**Comment by abernix** [comment]
> We'd also use this feature [apollographql.com/docs/apollo-server/api/plugin/usage-reporting/#includerequest](https://www.apollographql.com/docs/apollo-server/api/plugin/usage-reporting/#includerequest)
> But right now we have all of our traces double in apollo studio. ApolloGateway will send them with the operation name and the microservice will send another query
> <img alt="Bildschirmfoto 2020-10-06 um 16 48 35" width="380" src="https://user-images.githubusercontent.com/769789/95217713-ccd6ab00-07f3-11eb-99f7-33085bbf5ed0.png">

Since the Gateway request traces from the implementing services that it queries, the recommendation is to not have the implementing services setup to _also_ send traces.  We used to actually have a warning message in place when this configuration had been enabled inadvertently (which, because of the fact that we activate tracing automatically when the `APOLLO_KEY` or `ENGINE_API_KEY` is set in the environment, wasn't all that hard to do.  The suggestion in this case has been to not set the key in the implementing service, but that _may_ have changed to a degree which I don't immediately recall with https://github.com/apollographql/apollo-server/pull/4453/).

While I see how it's a use case that might work for you, it seems unnatural for me for the operation name to be threaded along to the downstream service as the operation name itself.  This is for at least a couple reasons that come to mind right away:

* The operation that the downstream service is merely a derivative of the incoming operation.  The name of the operation is decided by the client and assigning it to operations of dramatically different shapes (e.g., those that use `_entities` resolvers to reach into entity objects) seems like indirection.
* Each service in a federated graph that is involved in an operation's execution would receive the same operation name, adding another degree of nuanced variation appearing in logs, etc.

I am sympathetic to the downstream service receiving the name out-of-band — e.g. via `extensions`, though I also feel like a distributed tracing setup can facilitate this threading of information.  For example, I worry that if we go this route there are many other (mainly transport specific, but any variety of client-created properties) things which we might start passing along across services that might be better captured with distributed tracing configured throughout the lifetime of a request?

Just musing about this, but certainly something worth talking about.  These are just some initial thoughts.  I do think that, in the short-term, Apollo Studio should be displaying this in a coherent way right now and if it's not, that could be a bug or a misconfiguration (as noted above).

**Comment by abernix** [comment]
I should add, as an immediate term option, rather than setting `operationName` on the request (which as you found, is problematic because it results in requesting the execution of a named operation which doesn't exist in the document the downstream service receives), you could just add a header with the information you desire to log on the service?

**Comment by Glen-Moonpig** [comment]
> I should add, as an immediate term option, rather than setting `operationName` on the request (which as you found, is problematic because it results in requesting the execution of a named operation which doesn't exist in the document the downstream service receives), you could just add a header with the information you desire to log on the service?

That is what I have done already; added a header with the operation name.

**Comment by abernix** [comment]
If we were to make the header setting of the `operationName` the default behavior of `RemoteGraphQLDataSource` — say as `apollo-orig-operation-name`, as an example — would there be any other properties from the original request that would be interesting for you to receive in a similar way?

**Comment by Glen-Moonpig** [comment]
> If we were to make the header setting of the `operationName` the default behavior of `RemoteGraphQLDataSource` — say as `apollo-orig-operation-name`, as an example — would there be any other properties from the original request that would be interesting for you to receive in a similar way?

The `apollographql-client-name` and `apollographql-client-version` headers also.

**Comment by abernix** [comment]
Ok, just to be clear though, I believe those headers (which are specifically for Studio) should be getting attached to traces from federated service and displaying properly in Apollo Studio _without_ being passed through.  I just want to make sure we're not working against the grain of the way the product is designed and introducing functionality that shouldn't be required if things are configured properly.

**Comment by Glen-Moonpig** [comment]
> Ok, just to be clear though, I believe those headers (which are specifically for Studio) should be getting attached to traces from federated service and displaying properly in Apollo Studio _without_ being passed through. I just want to make sure we're not working against the grain of the way the product is designed and introducing functionality that shouldn't be required if things are configured properly.

Apollo Studio is only a monitoring tool? Or does it also collect logs?

**Comment by abernix** [comment]
Those client headers are configurable via `generateClientInfo`, so it would be a bit more difficult to special-case them.  In the new Rust gateway, we are looking at new patterns for header threading that are more declarative and handled automatically by the Gateway (Stargate), so it's possible there is a more clearly defined solution on the way by virtue of work in that regard.


> Apollo Studio is only a monitoring tool? Or does it also collect logs?

It doesn't collect logs, but it should be showing full request traces, including the requests to implementing services, and automatically bucketing them by client based on the default headers or the `generateClientInfo` method's mappings.

**Comment by williamboman-pp** [comment]
> That is what I have done already; added a header with the operation name.

Where/how do you do this? Have you managed to make it work within `RemoteGraphQLDataSource#willSendRequest()`, or somewhere else?

**Comment by Glen-Moonpig** [comment]
> > That is what I have done already; added a header with the operation name.
> 
> Where/how do you do this? Have you managed to make it work within `RemoteGraphQLDataSource#willSendRequest()`, or somewhere else?

We have implemented a custom fetch, which is given to the `RemoteGraphQLDataSource` constructor. You cannot reliably use the `willSendRequest` hook because Apollo Server modifies the http request object afterwards in some scenarios.

**Comment by williamboman-pp** [comment]
> We have implemented a custom fetch, which is given to the `RemoteGraphQLDataSource` constructor. You cannot reliably use the `willSendRequest` hook because Apollo Server modifies the http request object afterwards in some scenarios.

Ah gotcha. How do you extract the operation name from the query payload? I'm struggling a bit with this part.

**Comment by Glen-Moonpig** [comment]
We keep a reference to the custom fetch in the RemoteGraphQLDataSource and for each request we

In our custom fetcher:
```typescript
setContext(context: CustomGraphQLContext) {
    this.context = context;
}
```

In RemoteGraphQLDataSource:
```typescript
class CustomGraphQLDataSource extends RemoteGraphQLDataSource {
    private readonly customFetch: CustomFetch;

    public constructor(
        url: string | undefined,
    ) {
        const fetcher = new CustomFetch();
        super({
            url: url,
            fetcher: (input, init) => fetcher.doFetch(input, init),
        });
        this.customFetch = fetcher;
    }

    async willSendRequest({
        request,
        context,
    }: {
        request: GraphQLRequest;
        context: CustomGraphQLContext;
    }) {
        this.customFetch.setContext(context);
    }
...
```

Its a little messy, but does the job...

**Comment by rtymchyk** [comment]
https://github.com/apollographql/federation/issues/395 was an earlier discussion on this - there's another solution someone posted there.

**Comment by abernix** [comment]
Good news! This should be improved by #1550 and that improvement will go out in a new release of the `2.x` packages next week!  Thanks for opening this originally and feedback very much welcome.
