### ISSUE TITLE
@apollo/gateway do not support last @nestjs/core 

### ISSUE THREAD

**Issue by 20vitality12** [apollographql/federation#1998]
I'm using all latest nestjs version(^9.0.0) and @apollo/gateway 2.0.5 and my api-gateway fail to start with error: 

`ERROR [ExceptionHandler] Nest can't resolve dependencies of the GraphQLModule (?, GqlModuleOptions, AbstractGraphQLDriver, GraphQLTypesLoader). Please make sure that the argument HttpAdapterHost at index [0] is available in the GraphQLModule context.`

**To fix this issue** i've change "@nestjs/core": "9.0.4" to "@nestjs/core": "8.4.7".
Also before fix, installing any dep inside api-gateway folder help me too.

**Comment by benweatherman** [comment]
howdy @20vitality12! It seems that fed2 support was recently added as part of https://github.com/nestjs/graphql/issues/2141#issuecomment-1190256528. I'm not super familiar with nestjs, but is there any chance that version could work for you also? Otherwise, would you mind putting together a quick reproduction of the issue to make sure we get it setup correctly?
