### ISSUE TITLE
buildSubgraphSchema - Does not handle 'modules' for resolvers

### ISSUE THREAD

**Issue by ajzozakiewicz** [apollographql/federation#2439]
The Apollo Server 4 migration docs show the support for modules with apollo-server.

https://www.apollographql.com/docs/apollo-server/migration/#modules

```
new ApolloServer({
  typeDefs: modules.map({ typeDefs } => typeDefs),
  resolvers: modules.map({ resolvers } => resolvers)
})
```

However, there seems to be a bug when using this pattern in sub-graphs. If we follow the same pattern and additionally wrap with `buildSubgraphSchema()` we get unexpected behavior.

```
new ApolloServer({ 
  schema: buildSubgraphSchema({
    typeDefs: modules.map({ typeDefs } => typeDefs),
    resolvers: modules.map({ resolvers } => resolvers)
  })
})
```

Actual Behavior:

For the above implementation. TypeDefs work properly. But with resolvers, only the first module is loaded. Selecting data outside the first resolver will result in a `null` data set.

```
{
  "data": {
    "turtles": null
  }
}
```

If we look at the source code, we see where the issue comes in.

For `TypeDefs` we see the code expecting a `modulesOrSDL` type. But for resolvers, it is expecting `GraphQLResolverMap` and not handling the module arrays

https://github.com/apollographql/federation/blob/77168fd932a4171bfb88163bcfa98fa0a8c2d48e/subgraph-js/src/schema-helper/buildSchemaFromSDL.ts#L107

Expected Behavior:

`@apollo/subgraph` should handle `modulesOrSDL` type for `buildSubGraphSchema()` 

NPM Version: `8.19.2`
Node Version: `18.12.1`
Apollo Version: 
```
    "@apollo/server": "4.4.0",
    "@apollo/subgraph": "2.3.2",
```

Full Example:

```
const { gql } = require('@apparatus/express-graphql-api')

const turtles = [{ species: 'BOX' }]
const monkeys = [{ species: 'CHIMPANZEE' }]

const turtleTypeDefs = gql`
  type Turtle {
    species: String!
  }

  extend type Query {
    turtles: [Turtle]
  }
`

const turtleResolvers = {
  Query: {
    turtles: () => turtles
  },
}

const monkeyTypeDefs = gql`
  type Monkey {
    species: String!
  }

  extend type Query {
    monkeys: [Monkey]
  }
`

const monkeyResolvers = {
  Query: {
    monkeys: () => monkeys
  },
}

const monkeyModule = {
  typeDefs: monkeyTypeDefs,
  resolver: monkeyResolvers
}

const turtleModule = {
  typeDefs: turtleTypeDefs,
  resolvers: turtleResolvers
}

const modules = [
  monkeyModule,
  turtleModule
]

const server = new ApolloServer({
  schema: buildSubgraphSchema({
    typeDefs: modules.map(m => m.typeDefs),
    resolvers: modules.map(m => m.resolvers)
  })
})
```

**Comment by trevor-scheer** [comment]
Hey @ajzozakiewicz, sorry for the confusion here. Apollo Server actually _dropped_ the `modules` option (the snippet you provided is simply a migration path to the `{ typeDefs, resolvers }` interface which we kept).

The signature that `buildSubgraphSchema` uses is slightly different and hasn't changed since its inception. Since you have `modules` in the shape `{ typeDefs, resolvers }[]` already, you can pass that directly into `buildSubgraphSchema` without any issue like so: `buildSubgraphSchema(modules)`.

We recommend TypeScript to our users, and you would've gotten a helpful error here about the types of `resolvers` being incompatible. If you don't use TypeScript, you can still benefit from _our_ library's typings in various ways. The easiest being to add `// @ts-check` at the top of your files if your editor supports it (VS Code does). Alternatively, you can create a `tsconfig.json` which sets `checkJs: true`.

**Comment by ajzozakiewicz** [comment]
Awesome, appreciate the response. This worked well for me. Must have misunderstood when I read the docs. Thanks again.
