### ISSUE TITLE
Get an error when `@requires` fieldset has an entity which is resolved by two separate clients

### ISSUE THREAD

**Issue by Ishad-M-I-M** [apollographql/federation#2591]
### Issue Description

Posted in Stackoverflow as a question.
https://stackoverflow.com/questions/76303596/apollo-gateway-gives-an-error-when-requires-fieldset-has-an-entity-which-is-r

### Link to Reproduction

https://github.com/Ishad-M-I-M/apollo_federation

### Reproduction Steps

```bash
npm install
npm start
```
Then send the following query document via apollo-sandbox or postman etc.
```graphql
query {
  product(id: "1") {
    id
    name
    price
    courier {
      id
      name
      shippingCharge
      tax
    }
    estimatedShippingCharge
  }
}
```

**Comment by dariuszkuc** [comment]
Hello 👋 
There are few issues with your example project
- carrier graph
  - you define `shippingCharge` and `tax` fields as external but since you require them in products graph I'd assume those should be regular local fields
  - you don't define the values for the above fields either
  - no need for the `extend` types in Fed v2 (it was required in v1)
- products graph
  - product type 
  - referenced external fields from the `@requires` clause will be provided in the entity representation when resolving the `Product` type, you need to update the logic there accordingly

See https://github.com/Ishad-M-I-M/apollo_federation/pull/1
