### ISSUE TITLE
@authenticated name collision

### ISSUE THREAD

**Issue by jeffjakub** [apollographql/federation#2673]
### Issue Description

Please review test results for name collision error.

### Link to Reproduction

n/a

**Comment by dariuszkuc** [comment]
This is not a new issue but it looks like it surfaced because `@authenticated` is more common directive name than other fed v2 directive names.

Error is due to our Fed v1 -> Fed v2 subgraph schema upgrade logic. When we upgrade the schema we add default (latest) federation link definition that imports all fed v2 directives with default names (i.e. no namespacing). We then attempt to add all fed directive definitions verifying that if they are already defined in the schema, their definitions should match ([link](https://github.com/apollographql/federation/blob/main/internals-js/src/directiveAndTypeSpecification.ts#L155).

Simple test to repro (it fails with the same error for other fed v2 directives, e.g. `@tag`)

```js
it('existing @authenticated directive with fed 1', () => {
  const subgraphA = {
    typeDefs: gql`
      directive @authenticated(scope: [String!]) repeatable on FIELD_DEFINITION

      extend type Foo @key(fields: "id") {
        id: ID!
        protected: String @authenticated(scope: ["foo"])
      }
    `,
    name: 'subgraphA',
  };

  const subgraphB = {
    typeDefs: gql`
      type Query {
        foo: Foo
      }

      type Foo @key(fields: "id") {
        id: ID!
        name: String!
      }
      `,
    name: 'subgraphB',
  };

  debugger;
  const result = composeServices([subgraphA, subgraphB]);
  const schema = expectNoErrors(result); // blows up with error below
});
```

Error:
```
Array [
  Array [
    "DIRECTIVE_DEFINITION_INVALID",
      "[subgraphA] Invalid definition for directive \"@authenticated\": unknown/unsupported argument \"scope\"",
    ],
  Array [
    "DIRECTIVE_DEFINITION_INVALID",
      "[subgraphA] Invalid definition for directive \"@authenticated\": \"@authenticated\" should not be repeatable",
    ],
]
```

**Comment by dariuszkuc** [comment]
One potential fix is to change the upgrade logic to only include fed v1 directive definitions imports (as it was require to omit fed v1 directive definitions) so all the fed v2 specific directive are namespaced, i.e.

instead of
```
extend schema @link(url : "https://specs.apollo.dev/federation/v2.3", import : ["@authenticated", "@composeDirective", "@extends", "@external", "@key", "@inaccessible", "@interfaceObject", "@override", "@provides", "@requires", "@shareable", "@tag"])
```
apply
```
extend schema @link(url : "https://specs.apollo.dev/federation/v2.3", import : ["@extends", "@external", "@key", "@provides", "@requires"])
```
