### ISSUE TITLE
CSDL: revisit `fields` argument decision

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#272]
Ref: https://github.com/apollographql/apollo-server/pull/4489

This is an issue for tracking the progress and discussion around the changes made to the `fields` argument of federation directives within CSDL. Please continue further discussion here on this issue and see the linked PR for additional history and context.

**Comment by martijnwalraven** [comment]
I haven't been part of the discussion before, so this ship may have sailed, but I have a hard time seeing the reason for this change. As @glasser points out above, we don't actually want any piece of GraphQL to be valid here.

I think the idea is still that we only want to allow a list of `Selection`s. Parsing this by adding braces and extracting the resulting operation was just a hack because the `graphql-js` parser wasn't accessible. That has [recently changed](https://github.com/graphql/graphql-js/pull/2744), and we should be able to start parsing with a specific rule for the Rust parser as well.

In terms of the GraphQL grammar, you don't want a [`Document`](https://spec.graphql.org/June2018/#sec-Language.Document), but either a `SelectionSet` or a list of `Selection`s. Since a [`SelectionSet`](https://spec.graphql.org/June2018/#SelectionSet) is just a list of `Selection`s surrounded by `{` `}`, I don't see the value of requiring those braces. They would always be required and they would always come at the start and end of the string.

**Comment by glasser** [comment]
It looks like this has been at least partially taken into account over at https://github.com/apollo-specs/csdl/pull/1 (the naming at least, and it's an ongoing discussion if we want to consider going back to the no-brace version) so I'm going to close this one?
