### ISSUE TITLE
Incorrect Query Plan Generated when resolving multiple entities from the same subgraph.

### ISSUE THREAD

**Issue by harshitkumar31** [apollographql/federation#2792]
### Issue Description

We are upgrading to `@apollo/gateway`:`2.5.4` from `0.28.3`.
While most of our queries work fine, we've run into an issue where the query plan generated for the newer version of gateway seems to skip a keyed field (`_prefetch_`) but used to be part of the request in the older version.
I've attached the reproduction repo & the diff is best seen in the screenshot below
<img width="1398" alt="Screenshot 2023-09-26 at 8 37 00 PM" src="https://github.com/apollographql/federation/assets/15359962/b1bf2d05-36af-42e2-b3e4-76aa2df7cf09">

### Link to Reproduction

https://github.com/harshitkumar31/apollo-keys-issue

### Reproduction Steps

Follow the readme at https://github.com/harshitkumar31/apollo-keys-issue

**Comment by trevor-scheer** [comment]
This is a known change from Fed v1 to v2 and we consider this expected behavior.

In the example provided, the key which includes `_prefetch_` is seen as redundant in Fed 2.
>`@key(fields: "id _prefetch_") @key(fields: "id")`

This example unfortunately depends on some undefined behavior from Fed 1 - specifically, which key should the QP choose when either key will work?

Since Fed 2 removes the type ownership constraint, each subgraph is free to define _any_ keys that can be used to ID an entity within that subgraph, rather than just the keys made available / defined by the "owning" subgraph. Given this, the second key in the above example will always be preferred by the QP unambiguously since it's a subset of the first (thereby requiring strictly less information to resolve an entity than the first key).

If `_prefetch` is a required field to resolve a `C1`, the second key should be removed in order to force usage of the first key.
