### ISSUE TITLE
[Idea] Release debug versions of query-planner-wasm

### ISSUE THREAD

**Issue by barthez** [apollographql/federation#322]
Hello,

I'm having some troubles using rust query planner in our project with several, quite complex schema federated. I'm getting `RuntimeError: unreachable` from time to time on various queries (I cannot find any pattern and I didn't manage to have reproduction steps). My idea is to have `query-planner-wasm` package released both as `X.X.X` and `X.X.X-debug` so they could be used interchangeably. The `debug` version would include debug symbols so error stack traces would include rust function names instead of `wasm-function[x]` (according to [this article](https://rustwasm.github.io/book/reference/debugging.html)). Then these stack traces reported to error collecting system on staging machines could help us debug the problem (whether we have buggy schema federated or planner doesn't handle all the cases). 

Thanks!

**Comment by barthez** [comment]
No longer required, since there is no longer wasm query planner.

**Comment by abernix** [comment]
@barthez Ah, yes, sorry for not closing this.  This was indeed a great suggestion, by the way!  I even think it was plausible to use a different optimization level for `wasm-bindgen` that would not strip those symbols, rather than having another `-debug` version, but indeed it is very critical for those stack traces to be more valuable than they were.  Thanks for opening this originally!  We will be more considerate of this in any future follow-ups on this.

**Comment by abernix** [comment]
I hope you'll find the problem is gone! If it's not, please do open an issue with a reproduction and we'll be happy to take a look.

Also, just to be clear, even though we reverted back to the TypeScript query planner, we haven't given up on query planning in Rust in the long-term.  Our experimentation in compiling Rust to WASM did prove to be a valuable and great learning experiment for us, but we're comfortable going back to the TypeScript implementation for the time being.
