### ISSUE TITLE
Typescript compilation error using gateway server and nest.js

### ISSUE THREAD

**Issue by aa-bamboo** [apollographql/federation#334]
Typescript compilation error using @apollo/gateway server and nest.js.

Package @apollo/gateway 0.16.0

Expected: Application compiles successfully

Actual: A couple of typescript compilation errors

How to reproduce:
I've just followed the guide https://docs.nestjs.com/graphql/federation#federated-example-gateway
It's required to share the context.
I created a simple [application](https://github.com/aa-bamboo/apollo-gateway) for reproducing the problem. Check it please.

After starting the compilation error has occurred:

```
$ npm start

> apollo-gateway@0.0.1 start /tmp/apollo-gateway
> nest start

node_modules/@apollo/gateway/src/make-fetch-happen.d.ts:52:18 - error TS2300: Duplicate identifier 'fetch'.

52   export default fetch;
                    ~~~~~

  node_modules/@nestjs/graphql/node_modules/@apollo/gateway/src/make-fetch-happen.d.ts:52:18
    52   export default fetch;
                        ~~~~~
    'fetch' was also declared here.
node_modules/@nestjs/graphql/node_modules/@apollo/gateway/src/make-fetch-happen.d.ts:52:18 - error TS2300: Duplicate identifier 'fetch'.

52   export default fetch;
                    ~~~~~

  node_modules/@apollo/gateway/src/make-fetch-happen.d.ts:52:18
    52   export default fetch;
                        ~~~~~
    'fetch' was also declared here.
node_modules/apollo-server-core/dist/ApolloServer.d.ts:5:8 - error TS1259: Module '"/tmp/apollo-gateway/node_modules/@types/ws/index"' can only be default-imported using the 'esModuleInterop' flag

5 import WebSocket from 'ws';
         ~~~~~~~~~

  node_modules/@types/ws/index.d.ts:270:1
    270 export = WebSocket;
        ~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

Found 3 error(s).

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apollo-gateway@0.0.1 start: `nest start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apollo-gateway@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2020-05-22T08_31_58_584Z-debug.log
```

**Comment by jeffreychu-nexplore** [comment]
Same issue when following tutorial from nestjs.
https://docs.nestjs.com/graphql/federation#async-configuration

**Comment by glasser** [comment]
There appear to be two different issues here: the fetch issue and the ws issue.

For the fetch issue, it looks like what's going on relates to having multiple copies of `@apollo/gateway` installed (one directly and one inside `@nestjs/gateway`). Certain TypeScript features work poorly when you do that. We've also improved the `fetch` typing recently, which may or may not be relevant. If I start with your example and run `npm install @apollo/gateway@0.24.4 @nestjs/graphql@7.10.3` then `npm start` doesn't have the fetch issue. (0.24.4 isn't the latest version, but it's the version mentioned by the latest `@nestjs/graphql` release; they're [taken a renovate upgrade since then](https://github.com/nestjs/graphql/commit/83e6b3d147d2c6a1c903c6cf83e9b3b2c226f46c) but not released it.  I guess if you're using `@nestjs/graphql` you need to be careful to only use matching package versions?

For the ws issue, it looks like it's the same as https://github.com/apollographql/apollo-server/issues/1977 (it's happening in apollo-server-core, not something in this repo) and you can fix it by turning on esModuleInterop.

**Comment by sz-adminuser** [comment]
I had similar issue with fetch and your solution fixed it thanks @glasser

**Comment by tkssharma** [comment]
any help !!

[01:23:43] Starting compilation in watch mode...

node_modules/@apollo/gateway/src/make-fetch-happen.d.ts:58:18 - error TS2300: Duplicate identifier 'fetch'.

58   export default fetch;
                    ~~~~~

  node_modules/@nestjs/graphql/node_modules/@apollo/gateway/src/make-fetch-happen.d.ts:58:18
    58   export default fetch;
                        ~~~~~
    'fetch' was also declared here.

**Comment by trevor-scheer** [comment]
@tkssharma as @glasser mentioned above, it looks like you have two copies of `@apollo/gateway` installed in your project. If you need to install both `@apollo/gateway` and `@nestjs/graphql`, you probably need to find out which version of gateway is used by `@nestjs/graphql` and match that in your project.

Running the command `npm ls @apollo/gateway` will show you which versions of that package are being pulled in across your project. I suspect you'll see two different versions. If you make yours align with theirs, npm will be able to dedupe them and install only one copy.

If what I've said isn't helpful, I'd recommend opening a separate issue with a reproduction that we can `git clone` with directions on how to trigger the issue.
