### ISSUE TITLE
federation: queries for interface types require knowledge of concrete implementations

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/federation#336]
**Version:** `@apollo/gateway`@0.6.6
**Reproduction:** https://github.com/apollographql/federation-demo/compare/master...lennyburdette:interfaces?expand=1
**Related issues:** https://github.com/apollographql/apollo-server/pull/2848

I changed the federation-demo to use an interface for the `Product` type. I could get it to work, but not without some hacks that won't work in the real world.

The Reviews service has to know about `Product` implementations (`Book` and `Furniture`), even though it only knows about `Product.id`.

For this query: 

```gql
{
  me {
    reviews {
      product {
        id # doesn't work without https://github.com/apollographql/apollo-server/pull/2848
	name
        price
        inStock
        ... on Furniture {
          shippingEstimate
        }
      }
    }
  }
}
```

I see this in the query plan: 

```
Fetch(service: "reviews") {
  {
    ... on User {
      __typename
      id
    }
  } =>
  {
    ... on User {
      reviews {
        product {
          __typename
          id
          ... on Book {
            __typename
            id
          }
          ... on Furniture {
            __typename
            id
          }
        }
      }
    }
  }
},
```

Because the Gateway fetches `__typename`, I have to implement [`Product.__resolveType`](https://github.com/lennyburdette/federation-demo/blob/f0a5d9825e48312437d4d90908af8f3f2e12aa11/services/reviews/index.js#L59-L66) (in a gross way.)

This is often very hard and sometimes impossible, depending on how much information the service stores. Reviews doesn't know anything about Products other than the id, so there's no way for it to return the correct __typename.

Ideally, the query to Reviews would be:

``` 
{
  ... on User {
    reviews {
      body
      product {
        # ideally we wouldn't subselect __typename here so that the Reviews service
        # doesn't have to care about interface implementations
        id
      }
    }
  }
}
```

This is less of a problem for the Inventory service because:

* We use the ids from Reviews to call the Products service, which can return __typenames.
* We fetch Inventory fields using references (`{ __typename: "Furniture", id: "1" }`), so Inventory can just return the given __typename.

(There's also some unfortunate redundancy in Reviews and Inventory—we have to repeat __resolveReference functions for each interface implementation, but I can solve that on my side.)

**Comment by skk2142** [comment]
Any updates on this?

**Comment by wabrit** [comment]
I've hit this same problem; this (decoupling subgraphs via interfaces) is quite a common pattern in monolithic graphs,

The only workaround I can see is

- to redeclare the interface in the dependent graph and extend **all** of its known implementations
- have the dependent graph figure out the implementing type of an interface instance in order to construct the "reference stub" to return to the gateway

which is less than ideal because it couples the dependent graph too tightly to knowledge of what types implement the interface (leading to brittleness) and it forces an extra round trip on the part of the dependent graph to do the type resolution itself (assuming its even practical for it to do this).

I feel what is needed is for a subgraph to be able to return some kind of pseudo-reference to an interface instance `{ __interfacename: 'X', id: <id> }`, and for the "owning" subgraph of that interface to be able to declare a reference resolver on the **interface** _X_ that, given an id, can return the appropiate concrete instance of some type implementing X.

**Comment by cli00004** [comment]
Any updates on this? I'm now stuck on this very same issue

**Comment by pcmanus** [comment]
Sorry for the very long silence on this.

Fixing this is officially on [the roadmap](https://github.com/apollographql/federation/blob/main/ROADMAP.md#under-consideration) (it's the "Entity interfaces can be spread ..." bullet point) and fwiw I'm personally very keen on prioritizing this I do think it's an important part of improving separation of concerns. That said, and to be transparent, we're still in the process of prioritizing what we (at Apollo) want to do next and it's not a completely trivial issue, so a proper fix may still be a couple months away.

What I can share is that the way we're currently thinking of fixing this is essentially by allowing a subgraph to "implement" an interface as an object type locally. More concretely, and to take the Product/Review example from the description of this ticket, the plan is to allow to write (only including the relevant parts):
```graphql
# Subgraph 'products'
interface Product @key(fields: "id") {
  id: ID!
  name: String
  price: Int
}

type Book implements Product @key(fields: "id") {
  id: ID!
  name: String
  price: Int
  pages: Int
}

type Furniture implements Product @key(fields: "id") {
  id: ID!
  name: String
  price: Int
  weight: Int
}
```
```graphql
# Subgraph 'reviews'
type Review @key(fields: "id") {
  id: ID!
  body: String
  author: User
  product: Product
}

type Product @interfaceObject @key(fields: "id") {
  id: ID!
  reviews: [Review!]
}
```
The idea being that the "reviews" subgraph don't want to have anything to do with `Product` concrete implementations, it wants `Product` to be completely abstracted, and to do so it declares `Product` as an object type (instead of an interface) and mark it as an `@interfaceObject`. The later tells federation (and other readers) that `Product` is really an interface in the federated graph, but that this particular subgraph don't want to deal with the implementations.

The motivation for doing it this way is that this allows the "reviews" subgraph to both abstract `Product` but also be a completely normal graphQL schema. In particular, "reviews" needs nothing special and can be tested in isolation with no magic needed. It is the gateway/router that will be in charge, during queries, to do the proper translations (around `__typename` in particular) as needed.

I'll also note that another part of this is the support of `@key` on interface (the `@key` on `Product` in the "products" subgraph). This is what will allow, when you have a `Review`, to get its `product` fields. This part _will_ require a smal change for subgraph servers as they'll need to start supporting `__resolveReference` on interfaces, but that change should hopefully be relatively simple to implement.

There is more to be said on this, and I believe this proposal extends fairly naturally to more specific/complex use cases, but that can be expanded on later.

In any case, the reason I'm sharing this is also to solicit early feedback.

**Comment by pfyod** [comment]
@pcmanus Has there been any progress here?

**Comment by pcmanus** [comment]
> @pcmanus Has there been any progress here?

Sorry again for the spotty updates.

But we have starting working more concretely on the proposal I've laid out in my previous comment. And I've just created a dedicated issue for it: #2277. It's essentially still what I mention above, but I provide a bunch more details in that issue on the motivation and scope, and discuss some followups. Fwiw, I have a fair amount of it implemented, so I have to be able to share an initial patch for first look within a week or two (but obviously it'll take a bit more time to gather feedback on it and get proper testing, so still early to say when this can be expected into a release).

Of course, any feedback there is welcome.
