### ISSUE TITLE
Adding JWT authorization to Federated Service stops the gateway from running?

### ISSUE THREAD

**Issue by codef0rmer** [apollographql/federation#415]
I'm adding JWT authorization on `/graphql` federated service as follows and consuming the running service in Gateway. However, upon starting the gateway, I'm getting `Encountered error when loading at http://localhost:5001/graphql: 401: Unauthorized 🚀 Gateway ready at http://localhost:5000/graphql`

Is there any way I can add JWT authentication to the federated service and still run the gateway seamlessly? I intentionally do not want to apply JWT authorization to the gateway server since not all federated services need it at the moment.

```
// 5001 federated Graphql service
const jwt = require('express-jwt');
const cors = require('cors')
const jwksRsa = require('jwks-rsa');

const server = new ApolloServer({
    playground: playground,
    schema: federatedSchema,
});
const app = express();
app.use('/graphql', jwt({secret: (req, header, payload, done) => {
    if (payload) {
      jwksRsa.expressJwtSecret({
        cache: true,
        rateLimit: true,
        jwksRequestsPerMinute: 5,
        jwksUri: `${payload.iss}/.well-known/openid-configuration/jwks`
      })(req, header, payload, done);
    } else {
      return done('UnauthorizedError: Missing Access Token!', null);
    }
  }}), cors());

server.applyMiddleware({ app: app });
  app.listen({ port: 5001 }, () => console.log(`🚀 Gateway ready at http://localhost:5001${server.graphqlPath}`));
```

**Comment by abernix** [comment]
I'll close this since the new approach you found (for doing it differently than your original message) is the way we would generally suggest to do it today.

Also, since you posted your example, I'll just note that — on newer versions of Apollo Gateway/Server — it's no longer necessary to pass the `schema` and `executor` to `ApolloServer` (or call `gateway.load()`), but instead, you can just pass `gateway` to `ApolloServer`, which will take care of it for you.

Header threading (from the client, to subgraphs) is certainly/generally an interesting problem that we're looking to solve in a principled, declarative way within the graph itself, so it's useful that you opened this as an example.
