### ISSUE TITLE
fix(query-planner-js): `buildComposedSchema` doesn't preserve `@deprecated` usages on input values

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#635]
Reported by @sachindshinde - specifically calling `printSchema(buildComposedSchema(parse(supergraphSdl)))` loses `@deprecated` usages on input values.

**Comment by glasser** [comment]
What exactly do you mean by input values? Arguments definitions, input field definitions, or both?

Are we positive the loss is in `buildComposedSchema` rather than `printSchema`, or both?

(Note that support of these two features is still unmerged in the graphql-spec (https://github.com/graphql/graphql-spec/pull/805) although I do believe graphql-js already implements them.)

Is this just a matter of porting some changes from graphql-js to our copy/paste?
