### ISSUE TITLE
chore(tooling): Separate repo / npm package for common utils (@apollo/utils?)

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#685]
Some recent inspiration:
https://github.com/apollographql/apollo-tooling/pull/2274
(now squashed, but still relevant): https://github.com/apollographql/federation/commit/6c4261b0c57dea42de27eb808b81f01582c861a2

...and plenty of useful things in `apollo-graphql` and `apollo-tools` from the to-be-sunsetted tooling repo.

I'd love to see a generally useful utils package a la `@apollo/utils` which is home to useful and generic utility functions. This could be:
1) all kinds of utility fns like array utils (though these can and probably should be provided by small lodash packages)
2) useful generic TS types and predicates
3) anything else we find ourselves copy/pasting across multiple packages that wouldn't otherwise have a reason to depend on each other.
4) graphql specific utils that are still generic / useful in multiple applications

I know this has been a question in the past (mostly around what do we name it and who it should be useful for). I think a package like this should be considerate of various use cases (node, web) and should really only be home to non-application-specific utilities (though inclusive to graphql-specific utils).

**Comment by martijnwalraven** [comment]
I really like this idea, because the proliferation of utility/tools packages and duplicated code within our main packages is a pain. I do wonder whether it makes sense to combine web and server/tools here, because client already has its own utilities, and still needs to support [downcompiling to `es5`](https://github.com/apollographql/apollo-client/blob/90235f8f0cf6145a7da04b58c9f37760e57a99ed/tsconfig.json#L14), which I think we'd want to avoid for other uses.

**Comment by glasser** [comment]
My instinct is it might be a nice idea to have a single repo full of utils but to have it be a bunch of tiny packages instead of a single utils package which combines a lot of concerns into one.  In the interest of bundle sizes, being able to upgrade dependencies without need to do lots of work at once, etc.  eg utils that depend on graphql-js probably shouldn't be in the same package as utils with no deps.

**Comment by trevor-scheer** [comment]
This is done and turning out to be quite nice!
https://github.com/apollographql/apollo-utils
