### ISSUE TITLE
Add "core-js" as dependency to @apollo/federation

### ISSUE THREAD

**Issue by StarpTech** [apollographql/federation#692]
Upgrading from 0.23.0 to 0.23.1 broke my build with

```
 Error: Cannot find module 'core-js/features/array/flat'
  Require stack:
  - /home/starptech/repositories/starptech/demo/node_modules/@apollo/federation/dist/index.js
```

0.23.0

```
core-js@3.11.0
node_modules/core-js
  core-js@"^3.0.1" from apollo-env@0.6.6
  node_modules/apollo-env
    apollo-env@"^0.6.6" from apollo-graphql@0.6.1
    node_modules/apollo-graphql
      apollo-graphql@"^0.6.0" from @apollo/federation@0.23.0
      node_modules/@apollo/federation
        @apollo/federation@"0.23.0" from the root project
```

0.23.1

```
❯ npm why core-js
npm ERR! No dependencies found matching core-js
```

**Comment by glasser** [comment]
It looks like @abernix removed the dependency on `core-js` in https://github.com/apollographql/federation/pull/311 but didn't remove the references to it in `federation-js/src/index.ts`. Presumably this works in some contexts because core-js is a dependency of other stuff in the tree but not in contexts that strictly (correctly) enforce declared dependencies.

My guess is that the necessary fix is to remove the import rather than add the dependency. I'm not sure but I'll make a PR and send to @abernix to look at tomorrow!

**Comment by trevor-scheer** [comment]
Thanks for the report! This is resolved in the latest versions of federation and gateway:
```
- @apollo/federation@0.23.2
- @apollo/gateway@0.26.3
 ```
