### ISSUE TITLE
Support node 16

### ISSUE THREAD

**Issue by stephenh** [apollographql/federation#706]
Node 16 is out, but the `engines` value is limited to 15:

```
  "engines": {
    "node": ">=6 <15",
    "npm": "6.x"
  },
```

https://github.com/apollographql/federation/blob/main/package.json#L27

**Comment by marshalhayes** [comment]
+1

I stumbled upon this as well when setting up NestJS with GraphQL, which is essentially a wrapper to Apollo according to [their docs](https://docs.nestjs.com/graphql/quick-start).

If possible, I'd like the engine changed too. I'm not sure what implications this would have though. I guess an alternative would be to downgrade my node version to 15?

**Comment by glasser** [comment]
We're actively working on it: see #713.

Note that Apollo Server has a similar issue. In that case, the release-3.0 branch (which is under active development and we hope for a final release soon) officially supports Node 16. The current 2.x codebase does not support Node 16 because the apollo-server-hapi package is pinned (for back compat reasons) to an old version of Hapi that doesn't support Node 16. Hopefully "officially works and is tested in 3.x, works in practice other than Hapi in 2.x" will be sufficient; if not we can adapt.

**Comment by abernix** [comment]
As of the landing of #713, we're now testing Node.js 16 and since those tests are passing, the latest versions of the `@apollo/gateway` (`0.28.0`) and `@apollo/federation` (`0.24.0`) packages have just been published with Node.js 16 in their supported `engines` range for `node`.

**Comment by stephenh** [comment]
Awesome, thanks!
