### ISSUE TITLE
Missing operationName in __ApolloServiceHealthCheck__ query.

### ISSUE THREAD

**Issue by kutysam** [apollographql/federation#835]
This is regarding https://github.com/apollographql/federation/blob/main/gateway-js/src/index.ts#L670

Apollo has a healthcheck query 'query __ApolloServiceHealthCheck__ { __typename }'`
However, this query doesn't specify the operationName field within the JSON body.

In iGQL, when we send the same request, we do get a `operationName: __ApolloServiceHealthCheck__` within the POST body, You guys can turn on developmental tools and take a look at the request if needed.

operationName is very helpful in certain libraries where the have metrics just for operationName. It will be good to have an operationName for this, as well as serviceSDL

**Comment by glasser** [comment]
Specifying operationName alongside your operation is only needed in the special case where your operation document contains multiple top-level documents. It's just for disambiguation. See eg the [unofficial spec](https://graphql.org/learn/serving-over-http/):

> `operationName` is only required if multiple operations are present in the query.

What tooling do you have that requires it to always be specified?

**Comment by ChristopheVandePoel** [comment]
@glasser I get what you mean (both here and in the raised Pull Request for this). Would it make more sense that there is a way to configure health check headers in stead? In the case of the introspection query, there is the option to configure this. For the health check, the only option right now is to parse the query (and really _every_ query) and check if it is matching `query __ApolloServiceHealthCheck__ { __typename }`.

That would add overhead to every call, and it is fragile, because it is most likely considered Apollo Internals that can change. If the health-check function allowed to add a config to be included that sets the headers, it would solve both problems.

**Comment by kutysam** [comment]
> What tooling do you have that requires it to always be specified?
Tooling: https://github.com/netflix/dgs-framework/ Netflix DGS
It's not a requirement to let it be always specified, queries work with/ without it.
However, if we want to see metrics, they rely on the operationName. If operationName is not present, it will be anoynomous.
-> https://netflix.github.io/dgs/advanced/instrumentation/#shared-tags `gql.operation.name`

We are trying to differentiate user graphql queries and healthchecks within metrics and currently there is no way of doing it without the operationName flag. And if we do parse the body, as what Christophe mentioned, there is too much overhead if we check the body of every healthcheck.

**Comment by glasser** [comment]
I think it would be reasonable for us to provide some sort of HTTP header with health checks that make it clear that it's an HTTP header...

**Comment by glasser** [comment]
I"m going to solve this as part of #870.
- gateway will provide a special value for a new option to `GraphQLDataSource.process` when it's a health check
- this value will be passed on to `willSendRequest` as well in `GraphQLRemoteDataSource.process`
- so you can make a `GraphQLRemoteDataSource` subclass that uses `willSendRequest` to set whatever headers you want when it's a health check
