### ISSUE TITLE
Resolve array of ids

### ISSUE THREAD

**Issue by FBurner** [apollographql/federation#861]
Hi,

i implemented following type

```
type Campaign {
  _id: String!
  campaignMetrics: CampaignMetrics
  campaignName: String
  channels: [Channel]
  channel: Channel!
  created: DateTime!
  jobList: JobList
  mainPeriod: Period
  updated: DateTime!
}

type Channel {
  _id: ID! @external
}
```
Now channel is the external entity and has absolute no relation from their side to campaign and will never have.

But it seems i would have to save an id in the service that resolves channel  that breaks any design for the application.

Is there any feature to resolve an array properly otherwise i dont see how i can use apollo federation properly without breaking the design of my application?

**Comment by FBurner** [comment]
Hi,

i think this is very important because it makes it impossible to use appolo foundation

**Comment by trevor-scheer** [comment]
@FBurner it's a bit challenging for me to understand the problem you're facing with just this snippet. Can you provide the other related services (specifically the `Channel` owning service)? Also I think what you've provided is invalid. Since you've marked `_id` as `@external`, I think you are trying to extend the `Channel` entity. Instead, I would expect:
```graphql
extend type Channel @key(fields: "_id") {
  _id: ID! @external
}
```

It's true that both services must be able to resolve one of the `@key` fields on the `Channel` type (in this case `_id`). This is exactly how the gateway is able to retrieve and merge entities from the services where `Channel` is defined or extended. I think you're claiming that breaks the design of your application, but I don't understand how and it is a core requirement for type extension in this manner.

**Comment by FBurner** [comment]
As far as i understood its not possible to send an array as reference.

I would have to store an extra id in the subgraph with the collection of
the ids.

That is what breaks federation for me.

I can call the subgraph then directly with ids whar makes federation
unnecessary

Trevor Scheer ***@***.***> schrieb am Fr., 9. Juli 2021,
00:35:

**Comment by trevor-scheer** [comment]
Where are you sending an array as a reference? I see just the one `_id` field as a potential key in your example. Please elaborate on your example like I previously asked, since I still don't understand the problem you're alluding to.
If you're talking about using a list as a key, we have an example test case here: https://github.com/apollographql/federation/blob/main/gateway-js/src/__tests__/integration/list-key.test.ts

Are we talking about your `channels` field? If so, yes it certainly needs to be able to resolve those `_id`s , else how would it be able to associate the `Channel` from one service to another? Your `channels` resolver would need to return something like this: `[{ _id: 1 }, { _id: 2 }]`.

**Comment by FBurner** [comment]
I think i tried something before but it was wrong due to missinformation, was not correct.
Now it worked properly. 

Thank you and Sorry for the inconvenience.
