### ISSUE TITLE
issue and PR templates

### ISSUE THREAD

**Issue by ashleygwilliams** [apollographql/federation#99]
we have a pretty extensive explanation of how to file an issue/PR in our `CONTRIBUTING` doc, but it's not very discoverable there. Github issues let us put that context directly in the interface for folks writing issues. I would advocate that we start with *at least* an issue template for filing bugs- what do folks think?

**Comment by abernix** [comment]
I think this is a great idea!  In fact, I've been meaning apply this to the Apollo Server repository for a while and your opening of this issue was apparently the reignited inspiration I needed to execute.

So, NEW art ✨ :

* https://github.com/apollographql/apollo-server/issues/new/choose

And some existing art 🎨  in our org:

* https://github.com/apollographql/apollo-client/issues/new/choose
* https://github.com/apollographql/apollo-android/issues/new/choose

**Comment by Enrico2** [comment]
Done by @abernix
